### ISSUE TITLE
Create Find First One (FFO) Module

### ISSUE THREAD

**Issue by stweeks-pdx** [stweeks-pdx/ECE571IEEE754PointAdder#19]
For the Floating Point Adder, when normalizing the result after calculations we need to do a FFO to find the first one and what its index is, this will be used later for a barrel shifter to shift the amount a set number. We need to design this module and test it. We should also update the docs with the component interfaces, behavior, and any diagrams.

To test it we could create a Known Good Design (KGD) or we could come up with an exhaustive list and check against where the 1's index is (this could be done multiple ways). We might want to have multiple tests for this too? Good to begin this early.

**Comment by Hector-Cardenas** [comment]
I think the exhaustive list would be a good way to go about this. A script would be able to make a truth table for 32 bits and it would run fairly fast. My concern about using a KGD is that the iteration method may be slow, and if we pick a binary search implementation then there's overlap with some of the faster algorithms for our module.

**Comment by Hector-Cardenas** [comment]
I suppose a 33 (34?) case block would also be able to handle this fairly quickly as well but I'm not sure how clunky that is within a testbench.

**Comment by stweeks-pdx** [comment]
I think with a test bench we don't need to worry about clunky. I think having an easy to understand KGD module would just let us have a higher rate of confidence on the actual innerworkings of the system. I think the key here is that the more we cover and validate per component early on, the better chance we have at less debugging needed when everything comes together.
