### ISSUE TITLE
Create Float Type Data Structure

### ISSUE THREAD

**Issue by stweeks-pdx** [stweeks-pdx/ECE571IEEE754PointAdder#3]
Inside the packages format we will want to create a structure to represent an IEEE-754 floating point called float. It is 32-bits and should easily be represented as a packed structure to allow for ease of use when transferring data from a float to shortreal.

**Comment by Hector-Cardenas** [comment]
Hi

**Comment by Hector-Cardenas** [comment]
Hecctors comment
